### Sign in
POST http://notebook4g.vnptit.vn:8081/v1/login
Content-Type: application/json

{
    "username": "user",
    "password": "password123"
}


### Get Data Temp & Hum
GET https://api.open-meteo.com/v1/forecast?latitude=10.7476795&longitude=106.5911653&hourly=temperature_2m,relative_humidity_2m&forecast_days=1&timezone=Asia/Bangkok
Content-Type: application/json


### Get Data Tem and Hum
POST http://0.0.0.0:8000/api/sensors/create
Content-Type: application/json

{
    "device_name": "[KC] Air Quality 3C",
    "dataset": "aqi_index_mr_nhan",
    "device_token": "cmvmcxvn",
    "longitude": 106.5911653,
    "latitude": 10.7476795,
    "no2": 0.061,
    "so2": 0.059,
    "o3": 0.078,
    "pm25": 26,
    "pm10": 31,
    "aqi": 0,
    "no2Aqi": 0.061,
    "so2Aqi": 0.059,
    "o3Aqi": 0.078,
    "pm25Aqi": 26,
    "pm10Aqi": 31,
    "coAqi": 0.258,
    "temperature": 70,
    "humidity": 60,
    "timestamp": "2025-11-24T22:41:02.695+07:00"
}


### Get Data Tem and Hum
POST https://florus.hpcc.vn/api/external/data
Content-Type: application/json

{
    "device_name": "[KC] Air Quality 3C",
    "dataset": "aqi_index_mr_nhan",
    "device_token": "cmvmcxvn",
    "longitude": 106.5911653,
    "latitude": 10.7476795,
    "no2": 0.061,
    "so2": 0.059,
    "o3": 0.078,
    "pm25": 26,
    "pm10": 31,
    "aqi": 0,
    "no2Aqi": 0.061,
    "so2Aqi": 0.059,
    "o3Aqi": 0.078,
    "pm25Aqi": 26,
    "pm10Aqi": 31,
    "coAqi": 0.258,
    "temperature": 70,
    "humidity": 60,
    "timestamp": "2025-11-24T22:41:02.695+07:00"
}

### send data aqi
GET https://florus.hpcc.vn/api/aqi_server/prediction
Content-Type: application/json

{
    "timestamp": "2025-12-28 00:00:00",
    "station_id": "215",
    "limit": 20,
    "offset": 0,
    "flag": true
}


### prediction
POSt http://0.0.0.0:8000/api/sensors/predict
Content-Type: application/json

{
    "station_id":  "215",
    "timestamp": "2025-12-27T00:00:00"
}




### aqi
POST http://0.0.0.0:8000/api/sensors/aqi
Content-Type: application/json

{
    "pm25": 100.0,
    "pm10": 100.0,
    "no2": 100.0,
    "o3": 100.0,
    "so2": 100.0,
    "co": 100.0
}


### aqi
POST http://0.0.0.0:8000/api/sensors/create
Content-Type: application/json

{
    "pm25": 100.0,
    "pm10": 100.0,
    "no2": 100.0,
    "o3": 100.0,
    "so2": 100.0,
    "co": 100.0
}